version: "3.7"

services:
  consumer:
    build:
      context: ..
      dockerfile: docker/consumer/Dockerfile
    container_name: clickhouse-consumer
    restart: on-failure
    environment:
      REDPANDA_BROKERS: "redpanda:9092"
      CLICKHOUSE_HOST: "clickhouse"
      CLICKHOUSE_PORT: "9000"
    volumes:
      - ../src:/app/src
    networks:
      - coinbase-network
    healthcheck:
      test: ["CMD", "python", "-c", "import socket; socket.gethostbyname('redpanda'); socket.gethostbyname('clickhouse')"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

networks:
  coinbase-network:
    external: true