version: "3.7"

services:
  redpanda:
    image: redpandadata/redpanda:v24.2.18
    restart: on-failure
    container_name: redpanda
    hostname: redpanda
    ports:
      - "127.0.0.1:19092:19092"
      - "9092:9092"
    volumes:
      - redpanda-data:/var/lib/redpanda/data
    command:
      - redpanda
      - start
      - --kafka-addr PLAINTEXT://0.0.0.0:9092,OUTSIDE://0.0.0.0:19092
      - --advertise-kafka-addr PLAINTEXT://redpanda:9092,OUTSIDE://localhost:19092
      - --rpc-addr 0.0.0.0:33145
      - --advertise-rpc-addr redpanda:33145
      - --smp 1
      - --memory 1G
      - --mode dev-container
      - --default-log-level=warn
    healthcheck:
      test: ["CMD", "rpk", "cluster", "health"]
      interval: 10s
      timeout: 5s
      retries: 3

  redpanda-console:
    image: docker.redpanda.com/redpandadata/console:v2.3.1
    container_name: redpanda-console
    ports:
      - "8080:8080"
    depends_on:
      - redpanda
    volumes:
      - ./redpanda/console-config.yaml:/etc/redpanda-console/config.yaml:ro
    command: "/app/console"
    environment:
      KAFKA_BROKERS: "redpanda:9092"
      CONFIG_FILEPATH: "/etc/redpanda-console/config.yaml"

  clickhouse:
    image: clickhouse/clickhouse-server:25.1
    hostname: clickhouse
    restart: on-failure
    container_name: clickhouse
    ports:
      - 8123:8123  # HTTP interface
      - 9000:9000  # Native protocol
    depends_on:
      - redpanda
    environment:
      - CLICKHOUSE_DB=default
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=clickhouse_password
    volumes:
      - clickhouse-data:/var/lib/clickhouse
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8123/ping"]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  redpanda-data:
  clickhouse-data: