version: "3.8"
services:
  grafana:
    build:
      context: ..
      dockerfile: docker/grafana/Dockerfile
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
      - ../dashboards/grafana:/etc/grafana/provisioning/dashboards:ro
    environment:
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: "true"
      GF_SECURITY_ADMIN_PASSWORD: "admin"
volumes:
  grafana-storage: