version: "3.7"

services:
  producer:
    build:
      context: ..
      dockerfile: docker/producer/Dockerfile
    container_name: coinbase-producer
    restart: on-failure
    environment:
      REDPANDA_BROKERS: "redpanda:9092"
    volumes:
      - ../src:/app/src
    networks:
      - coinbase-network
    healthcheck:
      test: ["CMD", "python", "-c", "import socket; socket.gethostbyname('redpanda')"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

networks:
  coinbase-network:
    external: true 